name: CI/CD Pipeline - Examen

on:
  push:
    branches: [ main ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Instalamos las dependencias necesarias en el entorno global
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint fastapi uvicorn sqlalchemy pydantic

    # Ejecutamos Pylint posicionándonos dentro de la carpeta inventario
    - name: Run Pylint
      run: |
        cd inventario
        PYTHONPATH=. pylint app/main.py app/routers/items.py app/database.py app/models.py --disable=C,R,W0611,W0621